name: Test PR and push

on: [push, pull_request]
jobs:
  update_gh_pages:
    runs-on: ubuntu-latest
    name: Create and Upload DOCS
    steps:
      - name: Checkout
        uses: actions/checkout@v1 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: |
          npm ci
          npm install -g npm-install-peers
          npm install -g @angular/cli
          npm-install-peers
      - name: Build
        run: ./download_build_app.sh
        env:
          interceptor_key: ${{ secrets.interceptor_key }}