name: Update GH Pages

on: [push,pull_request]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    name: Create and Upload DOCS
    steps:
      - name: Checkout
        uses: actions/checkout@v1 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: |
          npm ci
          npm install -g npm-install-peers
          npm install -g @angular/cli
          npm-install-peers
      - name: Build
        run: ./download_build_app.sh
        env:
          interceptor_key: ${{ secrets.interceptor_key }}
          environment_config: ${{ secrets.environment_config }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./prerender/TrapezeClientNgDemo/
  publish_suite:
    runs-on: ubuntu-latest
    name: Publish
    needs: test_suite
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: ./prerender/TrapezeClientNgDemo/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          ACTIONS_DEPLOY_KEY: ${{ secrets.github_deploy_key }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./prerender/TrapezeClientNgDemo/
        with:
          emptyCommits: false